### ISSUE TITLE
Getting stuck in amaranth-mode when mixing red and blue

### ISSUE THREAD

**Issue by luxbock** [abo-abo/hydra#29] opened 2015-02-13 15:18 UTC
Starting with `emacs -Q`:

```emacs-lisp
(let ((default-directory "~/.emacs.d/elpa/"))
    (normal-top-level-add-subdirs-to-load-path))

(require 'hydra)

(defhydra hydra-window (global-map "C-w" :color amaranth)
  "window"
  ("k"   windmove-up "move-up" :color blue)
  ("j"   windmove-down "move-down" :color red)
  ("s"   split-window "split" :color blue))
```
I load the following and create a few split-windows with `C-w s`, which works fine. I can move windows up with `C-w k` just fine as well, but as soon as I use `C-w j` to try move down a window, the command executes but I get stuck in the amaranth mode with no way to get out. Neither `q` or `C-g` help either, so the only way I was able quit was by restarting Emacs.

**Comment by abo-abo** [comment] 2015-02-13 15:38
An amaranth body can only have blue and amaranth heads. Red ones don't
really make sense. Also note that `split-window` isn't a command, so
it's better to use sexp-style call for it.

The following works fine for me:

```cl
(defhydra hydra-test (global-map "C-w" :color amaranth)
  "window"
  ("k" windmove-up "move-up" :color blue)
  ("j" windmove-down "move-down")
  ("s" (split-window) "split" :color blue)
  ("q" nil "quit"))
```

Although it's a bit strange using amaranth here: you're locked into no-quit mode only after
<kbd>C-w j</kbd>. This code will lock you in right after <kbd>C-w</kbd>.

```
(global-set-key
 (kbd "C-w")
 (defhydra hydra-window (:color amaranth)
   "window"
   ("h" windmove-left "left")
   ("j" windmove-down "down")
   ("k" windmove-up "up")
   ("l" windmove-right "right")
   ("s" (split-window) "split")
   ("q" nil "cancel")))
```

**Comment by luxbock** [comment] 2015-02-13 15:52
Ah I see!

I think trying to define a body that uses amaranth with red heads should probably throw an error instead of passing for anyone else who might not have read the docs carefully enough. Being stuck in amaranth-mode with no way out can be rather frustrating.

**Comment by abo-abo** [comment] 2015-02-13 16:10
Actually, it's OK to do it, it's just redundant.
I'm not actually getting an error for this code:

```cl
(defhydra hydra-window (global-map "C-w" :color amaranth)
  "window"
  ("k" windmove-up "move-up" :color blue)
  ("j" windmove-down "move-down" :color red)
  ("s" (split-window) "split" :color blue))
```

I can press <kbd>C-w jjs</kbd> and it exits fine.

**Comment by luxbock** [comment] 2015-02-13 16:29
It appears to have been an issue with my older Emacs version (24.3). With this version the code above would lock me into amaranth state with no option of getting out. After I upgraded things appear to work fine.

**Comment by abo-abo** [comment] 2015-02-13 16:33
OK, I can reproduce it now, thanks.
I'll try to fix this soon. The issue didn't come up for me, since the Hydra quitting code has three
versions depending on Emacs version.

**Comment by abo-abo** [comment] 2015-02-20 17:23
Should be fixed now. If you still have a 24.3 around, try to check.

**Closed** 2015-02-20 17:22 UTC
