### ISSUE TITLE
The hydra pop out window erase all content of a buffer

### ISSUE THREAD

**Issue by deftsp** [abo-abo/hydra#114] opened 2015-04-22 00:48 UTC
To reproduce this problem:

1. open a elisp file, get a buffer named foo.el, then enable flycheck.
2.  move the cursor to a sexp (for exampe:   "_(defhydra hydra-git-gutter ......."), now flycheck will pop out a window named `*Flycheck error messages* `. 
3. Activate hydra, the pop window will erase all content of the buffer foo.el and the flycheck message window.  Pressing `q` to quit hydra, get  a mesage, "Buffer foo.el modifed; kill anyway? (y  or n)".  Choosing `n` not to kill, switch back to the buffer foo.el, the content of it is the help message of hydra. I have to `undo` to recover the the content.

If I set `hydra-lv` to nil, everthing is fine.

**Comment by abo-abo** [comment] 2015-04-22 05:45
> move the cursor to a sexp (for exampe: "_(defhydra hydra-git-gutter ......."), now flycheck will pop out a window

I'm stuck at this step, I don't get a Flycheck window. I've never used Flycheck, could you give me more details?

**Comment by deftsp** [comment] 2015-04-22 05:54
I have that problem only with flycheck window.   It seems lv-message choose the wrong window, I'll try to debug it.

**Comment by deftsp** [comment] 2015-04-22 14:34
Flycheck add  `flycheck-hide-error-buffer`  to `post-command-hook`.  When activate hydra, the `*Flycheck  error messages*` window will be quit,  which cause  `lv-window` will get a wrong window.  It seems not easy to solve it.


```
(defun flycheck-hide-error-buffer ()
  "Hide the Flycheck error buffer if necessary.

Hide the error buffer if there is no error under point."
  (-when-let* ((buffer (flycheck-error-message-buffer))
               (window (get-buffer-window buffer)))
    (unless (flycheck-overlays-at (point))
      (quit-window nil window))))
```

**Comment by abo-abo** [comment] 2015-04-22 14:43
> Flycheck add flycheck-hide-error-buffer to post-command-hook

Weird. Why is this necessary?

Also, I can't reproduce the issue without a recipe.

**Comment by deftsp** [comment] 2015-04-22 15:03
1. install flycheck
2. open the file foo.el with following content
3. enable flycheck by  M-x flycheck-mode
4. place the cursor  to the  `_`,       `_(defhydra hydra-git-gutter)...` , then flycheck will pop out a error message window.
5. activate hydra, you will get the problem.

```
(defhydra hydra-git-gutter (:body-pre (git-gutter-mode 1) :hint nil)
  "
Git gutter:
  _j_: next hunk        _s_tage hunk     _q_uit
  _k_: previous hunk    _r_evert hunk    _Q_uit and deactivate git-gutter
  ^ ^                   _p_opup hunk
  _h_: first hunk
  _l_: last hunk        set start _R_evision
"
  ("j" git-gutter:next-hunk)
  ("k" git-gutter:previous-hunk)
  ("h" (progn (goto-char (point-min))
              (git-gutter:next-hunk 1)))
  ("l" (progn (goto-char (point-min))
              (git-gutter:previous-hunk 1)))
  ("s" git-gutter:stage-hunk)
  ("r" git-gutter:revert-hunk)
  ("p" git-gutter:popup-hunk)
  ("R" git-gutter:set-start-revision)
  ("q" nil :color blue)
  ("Q" (progn (git-gutter-mode -1)
              ;; git-gutter-fringe doesn't seem to
              ;; clear the markup right away
              (sit-for 0.1)
              (git-gutter:clear))
   :color blue))
```

**Comment by abo-abo** [comment] 2015-04-22 15:20
I called <kbd>M-x</kbd> `hydra-git-gutter/body` and I get no issue. Both `*LV*` and `*Flycheck*` coexisted fine.

**Comment by deftsp** [comment] 2015-04-23 02:25
Finally, I found out the problem. After enable evil-mode, `default-major-mode` which is a obsolete variable will be set to `turn-on-evil-mode`. But I have  `(setq default-major-mode 'text-mode)` in my config file, when ` default-major-mode` is set to `text-mode` or `nil' , the problem I mentioned will occur.

**Comment by abo-abo** [comment] 2015-04-23 08:05
Good. If the problem is solved, and there's no input required from me, I'm closing this issue.

**Closed by abo-abo** 2015-04-23 08:05 UTC
