### ISSUE TITLE
Arrow keys don't work in amaranth hydras

### ISSUE THREAD

**Issue by jhonnyseven** [abo-abo/hydra#90] opened 2015-03-24 08:20 UTC
Arrow and function keys work in red, but not in amaranth hydras.
``` emacs-lisp
(defhydra test (:color amaranth)
  "foo"
  ("<left>" (message "left"))
  ("<f1>" (message "f1"))
  ("q" nil))
```

**Comment by abo-abo** [comment] 2015-03-24 10:17
Can't reproduce, I'm getting `"left"` message when I press <kbd>left</kbd>.
Can you eval `(symbol-function 'test/lambda-<left>)`?

**Comment by jhonnyseven** [comment] 2015-03-24 12:54
```
Call the head: `(message \"left\")'." (interactive) (hydra-disable) (catch (quote hydra-disable) (condition-case err (\
prog1 t (call-interactively (function (lambda nil (interactive) (message "left"))))) ((quit error) (message "%S" err) \
(if hydra-lv nil (sit-for 0.8)) nil)) (if hydra-is-helpful (progn (test/hint))) (setq hydra-last (hydra-set-transient-\
map (setq hydra-curr-map (quote (keymap (t lambda nil (interactive) (message "An amaranth Hydra can only exit through \
a blue head") (hydra-set-transient-map hydra-curr-map t) (when hydra-is-helpful (unless hydra-lv ...) (test/hint))) (7\
 . hydra-keyboard-quit) (113 . test/nil) (f1 . test/lambda-<f1>) (left . test/lambda-<left>) (switch-frame . hydra--ha\
ndle-switch-frame) (kp-subtract . hydra--negative-argument) (kp-9 . hydra--digit-argument) (kp-8 . hydra--digit-argume\
nt) ...))) t (function (lambda nil (hydra-cleanup)))))))
```

**Comment by abo-abo** [comment] 2015-03-24 13:12
You should set this before the eval, so that there are no `...`:

```cl
(setq eval-expression-print-length nil)
(setq eval-expression-print-level nil)
```

**Comment by jhonnyseven** [comment] 2015-03-24 13:20
```emacs-lisp
(lambda nil "Create a hydra with no body and the heads:\n\n\"<left>\":    `(message \"left\")',\n\"<f1>\":    `(message \"f1\")',\n\"q\":    `nil'\n\nThe body can be accessed via `test/body'.\n\nCall the head: `(message \"left\")'."
  (interactive)
  (hydra-disable)
  (catch 'hydra-disable
    (condition-case err
	(prog1 t
	  (call-interactively
	   #'(lambda nil
	       (interactive)
	       (message "left"))))
      ((quit error)
       (message "%S" err)
       (if hydra-lv nil
	 (sit-for 0.8))
       nil))
    (if hydra-is-helpful
	(progn
	  (test/hint)))
    (setq hydra-last
	  (hydra-set-transient-map
	   (setq hydra-curr-map
		 '(keymap
		   (t lambda nil
		      (interactive)
		      (message "An amaranth Hydra can only exit through a blue head")
		      (hydra-set-transient-map hydra-curr-map t)
		      (when hydra-is-helpful
			(unless hydra-lv
			  (sit-for 0.8))
			(test/hint)))
		   (7 . hydra-keyboard-quit)
		   (113 . test/nil)
		   (f1 . test/lambda-<f1>)
		   (left . test/lambda-<left>)
		   (switch-frame . hydra--handle-switch-frame)
		   (kp-subtract . hydra--negative-argument)
		   (kp-9 . hydra--digit-argument)
		   (kp-8 . hydra--digit-argument)
		   (kp-7 . hydra--digit-argument)
		   (kp-6 . hydra--digit-argument)
		   (kp-5 . hydra--digit-argument)
		   (kp-4 . hydra--digit-argument)
		   (kp-3 . hydra--digit-argument)
		   (kp-2 . hydra--digit-argument)
		   (kp-1 . hydra--digit-argument)
		   (kp-0 . hydra--digit-argument)
		   (57 . hydra--digit-argument)
		   (56 . hydra--digit-argument)
		   (55 . hydra--digit-argument)
		   (54 . hydra--digit-argument)
		   (53 . hydra--digit-argument)
		   (52 . hydra--digit-argument)
		   (51 . hydra--digit-argument)
		   (50 . hydra--digit-argument)
		   (49 . hydra--digit-argument)
		   (48 . hydra--digit-argument)
		   (45 . hydra--negative-argument)
		   (21 . hydra--universal-argument)))
	   t
	   #'(lambda nil
	       (hydra-cleanup))))))
```

**Comment by jhonnyseven** [comment] 2015-03-24 13:29
That `t` lambda in the keymap seems to be broken.

**Comment by abo-abo** [comment] 2015-03-24 13:35
The expansion looks the same as mine, and mine works fine.
What exactly is the problem you're getting by calling this function?
Also Emacs version?

**Comment by jhonnyseven** [comment] 2015-03-24 13:40
Is this correct:
```emacs-lisp
(t lambda nil
              (interactive)
              (message "An amaranth Hydra can only exit through a blue head")
              (hydra-set-transient-map hydra-curr-map t)
              (when hydra-is-helpful
            (unless hydra-lv
              (sit-for 0.8))
            (test/hint)))
```
I tested with GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu)
I get the message `An amaranth Hydra can only exit through a blue head` when I press left.

**Comment by abo-abo** [comment] 2015-03-24 13:42
Yes, it's correct. The binding for `t` will be called if none other match.
But you have `left` in that keymap as well, so all should work. Unless your left arrow does not
correspond to the `left` symbol. Can you check with `f1 k`?

**Comment by jhonnyseven** [comment] 2015-03-24 13:51
```emacs-lisp
(lambda nil "Create a hydra with no body and the heads:\n\n\"<left>\":    `(message \"left\")',\n\"<f1>\":    `(messag\
e \"f1\")',\n\"q\":    `nil'\n\nThe body can be accessed via `test/body'.\n\nCall the head: `(message \"f1\")'."
  (interactive)
  (hydra-disable)
  (catch 'hydra-disable
    (condition-case err
        (prog1 t
          (call-interactively
           #'(lambda nil
               (interactive)
               (message "f1"))))
      ((quit error)
       (message "%S" err)
       (if hydra-lv nil
         (sit-for 0.8))
       nil))
    (if hydra-is-helpful
        (progn
          (test/hint)))
    (setq hydra-last
          (hydra-set-transient-map
           (setq hydra-curr-map
                 '(keymap
                   (t lambda nil
                      (interactive)
                      (message "An amaranth Hydra can only exit through a blue head")
                      (hydra-set-transient-map hydra-curr-map t)
                      (when hydra-is-helpful
                        (unless hydra-lv
                          (sit-for 0.8))
                        (test/hint)))
                   (7 . hydra-keyboard-quit)
                   (113 . test/nil)
                   (f1 . test/lambda-<f1>)
                   (left . test/lambda-<left>)
                   (kp-subtract . hydra--negative-argument)
                   (kp-9 . hydra--digit-argument)
                   (kp-8 . hydra--digit-argument)
                   (kp-7 . hydra--digit-argument)
                   (kp-6 . hydra--digit-argument)
                   (kp-5 . hydra--digit-argument)
                   (kp-4 . hydra--digit-argument)
                   (kp-3 . hydra--digit-argument)
                   (kp-2 . hydra--digit-argument)
                   (kp-1 . hydra--digit-argument)
                   (kp-0 . hydra--digit-argument)
                   (57 . hydra--digit-argument)
                   (56 . hydra--digit-argument)
                   (55 . hydra--digit-argument)
                   (54 . hydra--digit-argument)
                   (53 . hydra--digit-argument)
                   (52 . hydra--digit-argument)
                   (51 . hydra--digit-argument)
                   (50 . hydra--digit-argument)
                   (49 . hydra--digit-argument)
                   (48 . hydra--digit-argument)
                   (45 . hydra--negative-argument)
                   (21 . hydra--universal-argument)))
           t
           #'(lambda nil
	       (hydra-cleanup))))))

```
Oh I see why the lambda isn't broken, clever ;)

**Comment by jhonnyseven** [comment] 2015-03-24 14:23
Sorry I misread you last message. What do you want me to check with `f1 k`? For left it says `<left>` is bound to `left-char`. Can't check what it's bount to in amaranth hydra.

**Comment by abo-abo** [comment] 2015-03-24 14:33
Yes, that's what I wanted you to check. So it seems that there should not be a problem, but there
is.  Can you try to redefine `test/lambda-<left>` using the current body, only remove the `t`
binding from the keymap.

**Comment by jhonnyseven** [comment] 2015-03-24 14:54
Same error.

Here's the test file I'm using:
```emacs-lisp
(setq eval-expression-print-length nil)
(setq eval-expression-print-level nil)

(add-to-list 'load-path "~/.emacs.d/vendor2/hydra")
  (require 'hydra)

(defhydra test-amaranth (:color amaranth)
  "test-amaranth"
  ("<left>" (message "left"))
  ("<f1>" (message "f1"))
  ("a" (message "a"))
  ("q" nil))

(defhydra test-red (:color red)
  "test-red"
  ("<left>" (message "left"))
  ("<f1>" (message "f1"))
  ("q" nil))

(global-set-key (kbd "t") 'test-amaranth/body)
(global-set-key (kbd "r") 'test-red/body)
(global-set-key (kbd "o")
		(lambda ()
		  (interactive)
		  (switch-to-buffer "*scratch*")
		  (insert (pp (symbol-function 'test-amaranth/lambda-<left>)))))
(global-set-key (kbd "i")
		(lambda ()
		  (interactive)
		  (switch-to-buffer "*scratch*")
		  (insert (pp (symbol-function 'test-red/lambda-<left>)))))


(defun test-amaranth/lambda-<left> ()
  "Create a hydra with no body and the heads:\n\n\"<left>\":    `(message \"left\")',\n\"<f1>\":    `(messag\
e \"f1\")',\n\"a\":    `(message \"a\")',\n\"q\":    `nil'\n\nThe body can be accessed via `test-amaranth/body'.\n\nCa\
ll the head: `(message \"left\")'."
  (interactive)
  (hydra-disable)
  (catch 'hydra-disable
    (condition-case err
        (prog1 t
          (call-interactively
           #'(lambda nil
               (interactive)
               (message "left"))))
      ((quit error)
       (message "%S" err)
       (if hydra-lv nil
         (sit-for 0.8))
       nil))
    (if hydra-is-helpful
        (progn
          (test-amaranth/hint)))
    (setq hydra-last
          (hydra-set-transient-map
           (setq hydra-curr-map
                 '(keymap
                   ;; (t lambda nil
                   ;;    (interactive)
                   ;;    (message "An amaranth Hydra can only exit through a blue head")
                   ;;    (hydra-set-transient-map hydra-curr-map t)
                   ;;    (when hydra-is-helpful
                   ;;      (unless hydra-lv
                   ;;        (sit-for 0.8))
                   ;;      (test-amaranth/hint)))
                   (7 . hydra-keyboard-quit)
                   (113 . test-amaranth/nil)
                   (97 . test-amaranth/lambda-a)
                   (f1 . test-amaranth/lambda-<f1>)
                   (left . test-amaranth/lambda-<left>)
                   (kp-subtract . hydra--negative-argument)
                   (kp-9 . hydra--digit-argument)
                   (kp-8 . hydra--digit-argument)
                   (kp-7 . hydra--digit-argument)
                   (kp-6 . hydra--digit-argument)
                   (kp-5 . hydra--digit-argument)
                   (kp-4 . hydra--digit-argument)
                   (kp-3 . hydra--digit-argument)
                   (kp-2 . hydra--digit-argument)
                   (kp-1 . hydra--digit-argument)
                   (kp-0 . hydra--digit-argument)
                   (57 . hydra--digit-argument)
                   (56 . hydra--digit-argument)
                   (55 . hydra--digit-argument)
                   (54 . hydra--digit-argument)
                   (53 . hydra--digit-argument)
                   (52 . hydra--digit-argument)
                   (51 . hydra--digit-argument)
                   (50 . hydra--digit-argument)
                   (49 . hydra--digit-argument)
                   (48 . hydra--digit-argument)
                   (45 . hydra--negative-argument)
                   (21 . hydra--universal-argument)))
           t
           #'(lambda nil
	       (hydra-cleanup))))))



(setq eval-expression-print-length nil)
(setq eval-expression-print-level nil)

(add-to-list 'load-path "~/.emacs.d/vendor2/hydra")
  (require 'hydra)

(defhydra test (:color amaranth)
  "foo"
  ("<left>" (message "left"))
  ("<f1>" (message "f1"))
  ("a" (message "a"))
  ("q" nil))

(defhydra test-b (:color red)
  "foo"
  ("<left>" (message "left"))
  ("<f1>" (message "f1"))
  ("q" nil))

(global-set-key (kbd "t") 'test/body) 
(global-set-key (kbd "r") 'test-b/body)
(global-set-key (kbd "o")
		(lambda ()
		  (interactive)
		  (switch-to-buffer "*scratch*")
		  (insert (pp (symbol-function 'test/lambda-<f1>)))))
(global-set-key (kbd "i")
		(lambda ()
		  (interactive)
		  (switch-to-buffer "*scratch*")
		  (insert (pp (symbol-function 'test-b/lambda-<left>)))))
(defun test/lambda-<f1>
  "Create a hydra with no body and the heads:\n\n\"<left>\":    `(message \"left\")',\n\"<f1>\":    `(messag\
e \"f1\")',\n\"q\":    `nil'\n\nThe body can be accessed via `test/body'.\n\nCall the head: `(message \"f1\")'."
  (interactive)
  (hydra-disable)
  (catch 'hydra-disable
    (condition-case err
	(prog1 t
	  (call-interactively
	   #'(lambda nil
	       (interactive)
	       (message "f1"))))
      ((quit error)
       (message "%S" err)
       (if hydra-lv nil
	 (sit-for 0.8))
       nil))
    (if hydra-is-helpful
	(progn
	  (test/hint)))
    (setq hydra-last
	  (hydra-set-transient-map
	   (setq hydra-curr-map
		 '(keymap
		   (7 . hydra-keyboard-quit)
		   (113 . test/nil)
		   (f1 . test/lambda-<f1>)
		   (left . test/lambda-<left>)
		   (kp-subtract . hydra--negative-argument)
		   (kp-9 . hydra--digit-argument)
		   (kp-8 . hydra--digit-argument)
		   (kp-7 . hydra--digit-argument)
		   (kp-6 . hydra--digit-argument)
		   (kp-5 . hydra--digit-argument)
		   (kp-4 . hydra--digit-argument)
		   (kp-3 . hydra--digit-argument)
		   (kp-2 . hydra--digit-argument)
		   (kp-1 . hydra--digit-argument)
		   (kp-0 . hydra--digit-argument)
		   (57 . hydra--digit-argument)
		   (56 . hydra--digit-argument)
		   (55 . hydra--digit-argument)
		   (54 . hydra--digit-argument)
		   (53 . hydra--digit-argument)
		   (52 . hydra--digit-argument)
		   (51 . hydra--digit-argument)
		   (50 . hydra--digit-argument)
		   (49 . hydra--digit-argument)
		   (48 . hydra--digit-argument)
		   (45 . hydra--negative-argument)
		   (21 . hydra--universal-argument)
		   
		   ))
	   t
	   #'(lambda nil
	       (hydra-cleanup))))))
```

**Comment by jhonnyseven** [comment] 2015-03-24 14:56
Sorry there's some mess. The file came twice, only the first is OK.

**Comment by abo-abo** [comment] 2015-03-24 17:32
So you call `test-amaranth/lambda-<left>` with the `t` part commented out. And you get what?

**Comment by jhonnyseven** [comment] 2015-03-24 18:02
Sorry I redefined the wrong function `test-amaranth/lambda-<left>`.

Body with t commented out works correctly and prints `left`.

**Comment by abo-abo** [comment] 2015-03-24 18:06
OK, make sure that it errors if you un-comment.

Then, move the `t` statement all the way to the end of the keymap. See if that makes a difference.

**Comment by jhonnyseven** [comment] 2015-03-24 18:10
`(message "keys '%s'" (this-command-keys))` in the `t` lamba prints `keys 'D'`

**Comment by jhonnyseven** [comment] 2015-03-24 18:11
I tried the end trick, no difference.

**Comment by jhonnyseven** [comment] 2015-03-24 18:12
Probably something terminal related. It's strange the red hydra works though.

**Comment by jhonnyseven** [comment] 2015-03-24 18:16
```
An amaranth Hydra can only exit through a blue head
keys '^['
An amaranth Hydra can only exit through a blue head
keys '['
An amaranth Hydra can only exit through a blue head
keys 'D'
```
Oops. Didn't see that.

**Comment by abo-abo** [comment] 2015-03-24 18:16
> Probably something terminal related

And finally, the cause. Next time someone asks you the Emacs version, make sure to mention that
you're running it in a terminal. I can now reproduce the issue. I'll try to look into it at some
point this week.

**Comment by jhonnyseven** [comment] 2015-03-24 18:20
Sorry didn't think that. I thought everyone ran emacs in terminal :)

**Comment by abo-abo** [comment] 2015-03-24 18:26
I almost never run Emacs in a terminal. It looks so weird without a fringe. And the key bindings are
weird. And the screen refresh rate. And the faces. It's all weird.

**Comment by abo-abo** [comment] 2015-03-31 10:04
I'm trying to look at this issue, but how in the world can I copy something from Firefox and paste
it into `emacs -nw`?

**Comment by jhonnyseven** [comment] 2015-03-31 10:14
I've been using this:
```emacs-lisp
(defun paste-from-x-clipboard ()
  (interactive)
  (shell-command-on-region (point) (point) "xsel" (current-buffer) t))
```
It pastes from the x selection. You can give options to xsel if you want to use clipboard.

**Comment by abo-abo** [comment] 2015-03-31 10:29
OK, I got it, in terminal:

- instead of receiving F1 (key code 67), I get key code 80.
- instead of receiving left (key code 113), I get key code 68.

You can check it by evaling this code:

```cl
(set (defvar test/keymap nil "Keymap for test.")
     (quote (keymap (t lambda nil (interactive)
                       (message "An amaranth Hydra can only exit through a blue head")
                       (setq dbg-kv (this-command-keys-vector))
                       (hydra-set-transient-map hydra-curr-map t)
                       (when hydra-is-helpful (unless hydra-lv (sit-for 0.8))
                             (test/hint)))
                    (7 . hydra-keyboard-quit)
                    (113 . test/nil)
                    (f1 . test/lambda-<f1>)
                    (80 . test/lambda-<f1>)
                    (left . test/lambda-<left>)
                    (68 . test/lambda-<left>)
                    (switch-frame . hydra--handle-switch-frame)
                    (kp-subtract . hydra--negative-argument)
                    (kp-9 . hydra--digit-argument)
                    (kp-8 . hydra--digit-argument)
                    (kp-7 . hydra--digit-argument)
                    (kp-6 . hydra--digit-argument)
                    (kp-5 . hydra--digit-argument)
                    (kp-4 . hydra--digit-argument)
                    (kp-3 . hydra--digit-argument)
                    (kp-2 . hydra--digit-argument)
                    (kp-1 . hydra--digit-argument)
                    (kp-0 . hydra--digit-argument)
                    (57 . hydra--digit-argument)
                    (56 . hydra--digit-argument)
                    (55 . hydra--digit-argument)
                    (54 . hydra--digit-argument)
                    (53 . hydra--digit-argument)
                    (52 . hydra--digit-argument)
                    (51 . hydra--digit-argument)
                    (50 . hydra--digit-argument)
                    (49 . hydra--digit-argument)
                    (48 . hydra--digit-argument)
                    (45 . hydra--negative-argument)
                    (21 . hydra--universal-argument))))
```

Now only to understand how 80 is linked to 67 and how 68 is linked to 113.

**Comment by jhonnyseven** [comment] 2015-03-31 10:49
I checked with C-q in bash:
Left arrow gives `^[[D` and `F1` gives `^[[11~`.

**Comment by abo-abo** [comment] 2015-03-31 10:52
> Left arrow gives ^[[D and F1 gives ^[[11~

I don't know what this means.

**Comment by jhonnyseven** [comment] 2015-03-31 10:52
You've probably seen the [translation keymaps](https://www.gnu.org/software/emacs/manual/html_node/elisp/Translation-Keymaps.html).

**Comment by jhonnyseven** [comment] 2015-03-31 10:54
Those are the actual keys that are sent to emacs whenever I press `<left>` or `F1`. I think `^[` actually is the escape key, but otherwise they are as is.

**Comment by jhonnyseven** [comment] 2015-03-31 10:59
Running this `(read-key-sequence "?")` and pressing left gives `[left]`.

**Comment by abo-abo** [comment] 2015-03-31 13:44
Try the fix in `term-fix` branch. It should work just for arrows and functional keys, not all
elements of `input-decode-map`.

**Comment by jhonnyseven** [comment] 2015-03-31 14:25
Seems to work. Altough first time pressing `<left>` or `f1` after entering hydra gives this message: `setq: Symbol's value as variable is void: test/keymap`.

**Comment by abo-abo** [comment] 2015-03-31 15:57
OK, try again. This is a completely different approach.
It may be buggy, but it's supposed to solve all problems, including the shortcuts in the terminal
and the prefixes in pink hydras.

**Comment by jhonnyseven** [comment] 2015-03-31 17:00
I'm getting this on 24.3.1 `Symbol's function definition is void: internal-push-keymap`

**Comment by abo-abo** [comment] 2015-03-31 17:03
That's why that function starts with `internal-`:).

Can you try on 24.4, that function should be available there. It will be a while before I port
the new definition of `hydra-set-transient-map` to all Emacs versions.

**Comment by jhonnyseven** [comment] 2015-03-31 17:26
At least the cursors and f1 works on 24.4.

**Comment by jhonnyseven** [comment] 2015-04-09 09:37
The `switch-frame` event doesn't get through in terminal (gtk version works, 24.4.1).

**Comment by abo-abo** [comment] 2015-04-09 09:47
Funny, I was just working on hydra for the first time in a week.
Could you please test the latest commit? The basic stuff should work, but it's a lot of changes.

**Comment by jhonnyseven** [comment] 2015-04-09 10:10
Yeah, I was away for a week too.

I tried the latest, same thing.

I actually get this when I press `j`. 
```
An amaranth Hydra can only exit through a blue head [(switch-frame #<frame F3 0x3b0a828>)]
An amaranth Hydra can only exit through a blue head [106]
```
That's `(this-command-keys-vector)` in the end.

**Comment by abo-abo** [comment] 2015-04-09 10:21
> I tried the latest, same thing.
> 
> I actually get this when I press j.

You'll have to be more specific. I assume that you're using the amaranth hydra `test` from the top.
What keys are you pressing?

**Comment by jhonnyseven** [comment] 2015-04-09 10:35
Oh right, forgot some context.

Yes the hydra from top. 

Open emacs server and connect two terminal emulators to it. In one frame run the test hydra. Switch to the other frame and try to press some keys. Expected behaviour is that the hydra exits and keypress goes through to the second frame. But now I just get those two messages.

This was fixed in #73 once.

**Comment by abo-abo** [comment] 2015-04-09 11:15
This new setup is simplifying a lot of things.
Please test further if all your hydras are working fine, I plan to merge this into master soon.

**Comment by jhonnyseven** [comment] 2015-04-09 13:09
Frame switching seems to work.

It seems like `:post` is now called twice:

```emacs-lisp
(defhydra test (:color amaranth :post (message "post"))
  "foo"
  ("<left>" (message "left") :exit t)
  ("<f1>" (message "f1"))
  ("q" nil))
```
Gives
```
post
left
post
```

**Comment by jhonnyseven** [comment] 2015-04-09 16:22
Would it be possible to retain the latter `:post`, the one after the head command? That's how it worked before.

**Comment by abo-abo** [comment] 2015-04-09 16:49
> Would it be possible to retain the latter :post, the one after the head command? That's how it worked before.

I think it makes more sense now as it is, the current output should be:

    post
    left

which is good if `left` is a new hydra. The old one has to completely
exit before the new one starts.

Do you have a use-case?

**Comment by jhonnyseven** [comment] 2015-04-09 17:44
Well I've been using basically this code here in the last heading: https://github.com/abo-abo/hydra/wiki/Nesting-Hydras

I have a teal hydra `vi-select` that exits after each head and calls `visit-hydra-post` in the `:post`. That calls the previous hydra if there was any. Now that the `:post` is called before the head, I'd have to make sure it's ok to call a head in a new hydra, whatever that hydra is.

I'd have to change my hydras and that visit-hydra thing to see if it causes any problems. Or maybe I'll just change all the exit heads to `(progn (old-head) (call-post2))`.

**Comment by jhonnyseven** [comment] 2015-04-09 17:54
Both orders make sense to me. 

Currently, if you move to another hydra with a direct `/body` call the `:post` is called before entering the new hydra. In the other order, any head is called in the current hydra, before the hydra "state" is torn down in the `:post`.

**Comment by abo-abo** [comment] 2015-04-09 18:12
> I have a teal hydra vi-select that exits after each head and calls visit-hydra-post in the :post.

That's the source of confusion. I have zero use-cases for `:post`, except the cute
changing of the cursor color. So I don't fully understand the best way to implement this.

I think the idea of only one hydra being active at a time, and zero intersection time
between the hydras that call each other is a good one.  Can you adapt to this new rule
set? If it's too difficult, show me your use case completely, I'll try to figure it out.

**Comment by jhonnyseven** [comment] 2015-04-09 18:46
> I think the idea of only one hydra being active at a time, and zero intersection time
> between the hydras that call each other is a good one.

This is good idea, and I've worked like this with `visit-hydra`. The new hydra is entered as the last step in `:post`. The next hydra is only queued up in the exit head.

I'd like to also have the assumption that all hydra heads are called between `:body-pre` and `:post`. I.e. they are called in the current hydra's "state". 

If you think this current order is the best, I think I'll have to go with `(progn (old-head) (call-post2))` and not use `:post` at all.

Maybe `:post` could use a better name if the order stays. Maybe `:pre-exit-head` or just `:pre-exit`.

**Comment by abo-abo** [comment] 2015-04-09 19:10
> all hydra heads are called between :body-pre and :post

This can't be fulfilled, since `:body-pre` is only called for `foo/body`.
It's not called for `foo/func-1` which also enters the `foo` hydra.

> I'd like to also have the assumption that all hydra heads are called between :body-pre and :post. I.e. they are called in the current hydra's "state". (A1)
> 
> If you think this current order is the best, I think I'll have to go with (progn (old-head) (call-post2)) and not use :post at all to achieve A1.

For me, `:post` is the equivalent of C++ destructor: it has to release
all resources (which were usually acquired in `:pre` or `:body-pre`).
That's why I think it's in an appropriate place.

> (progn (old-head) (call-post2))

I have no problem adding another keyword, say `:foo` that adds this
functionality.  Assuming that `hydra-1` calls `hydra-2`, the order should be
(the head is, of course, blue):

1. hydra-1-pre
2. hydra-1-post
3. call-interactively 'foo
4. hydra-1-foo

The item 3 expands to:

1. hydra-2-body-pre or hydra-2-pre
2. hydra-2-foo

So together it becomes:

1. hydra-1-pre
2. hydra-1-post
3. hydra-2-body-pre or hydra-2-pre
4. hydra-2-foo
5. hydra-1-foo

From this setup, it also follows that no new resources should be acquired in `:foo`.
Is this order clear/OK? You can suggest your preferred keyword name for `:foo`.

> Maybe :post could use a better name if the order stays. Maybe :pre-exit-head or just :pre-exit.

`:pre-exit` sounds good, or maybe `:before-exit`.

**Comment by jhonnyseven** [comment] 2015-04-09 19:52
> This can't be fulfilled, since :body-pre is only called for foo/body.
> It's not called for foo/func-1 which also enters the foo hydra.

Oh I hadn't tought about entering from something else than body. Thanks.

> For me, :post is the equivalent of C++ destructor: it has to release
> all resources (which were usually acquired in :pre or :body-pre).
 
But it doesn't make much sense to first call the destructor and then do something with the object (hydra) by calling the exit head. (Maybe I'm using wrong terminology, by exit head I actually just mean the `foo` part in `("f" foo :exit t)`)

> I have no problem adding another keyword, say :foo that adds this
> functionality. 

Sounds good.

> Is this order clear/OK?

It's both.

If `:post` becomes `:pre-exit` then `:foo` should be `:post-exit`. Or `:before-exit` and `:after-exit`.
I don't know if it's good or bad idea to add one more pre. It would be confusion and consistency at the same time. :P. Maybe `:before-exit` and `:after-exit` is better. Either way sounds good to me.

**Comment by abo-abo** [comment] 2015-04-09 20:11
> But it doesn't make much sense to first call the destructor and then do something with the object (hydra) by calling the exit head

The way I think about it, at the time when a blue head is called, the hydra doesn't exist any more.
The main resource of the hydra is the `set-transient-map` which is an overriding map that it
acquires.  It *has* to be released or Emacs will become unstable. The way it is now, I release it as
soon as possible, and indeed when it's not needed any more.

Otherwise, I'd have to pass a callback to the blue head to release the map.  And then the blue head
would have to pass the callback to whatever it calls.  And so on. I've seen this situation when I
tried to use `ace-jump-mode` in `ace-window`. That code wasn't clear or pretty.

If Elisp was more advanced, maybe it would be possible to do something else.  But as it is now,
releasing the resource early is the way to go.

> Or :before-exit and :after-exit.

OK, I'll try to add this on the weekend, maybe tomorrow.

**Comment by abo-abo** [comment] 2015-04-11 15:32
I've merged the changes into `master`, and also updated the wiki page for nesting hydras.
Let me know if you have any further questions.

**Closed by abo-abo** 2015-04-11 15:32 UTC

**Comment by jhonnyseven** [comment] 2015-04-11 16:54
I'm getting `:after-exit`s in non-exit heads:

```emacs-lisp
(defhydra test (:color amaranth :before-exit (message "before") :after-exit (message "after"))
  "foo"
  ("<left>" (message "left") :exit t)
  ("<f1>" (message "f1"))
  ("q" nil))

---

test/lambda-<f1>:
 (lambda nil "Create a hydra with no body and the heads:\n\n\"<left>\":    `(message \"left\")',\n\"<f1>\":    \
`(message \"f1\")',\n\"q\":    `nil'\n\nThe body can be accessed via `test/body'.\n\nCall the head: `(message \"f1\")'\
."
  (interactive)
  (hydra-default-pre)
  (condition-case err
      (call-interactively
       #'(lambda nil
           (interactive)
           (message "f1")))
    ((quit error)
     (message "%S" err)
     (if hydra-lv nil
       (sit-for 0.8))))
  (if hydra-is-helpful
      (progn
	(test/hint)))
  (hydra-set-transient-map test/keymap
                           #'(lambda nil
                               (hydra-keyboard-quit)
                               (message "before"))
                           'warn)
  (message "after")) <------------------------------------- HERE

```

**Comment by abo-abo** [comment] 2015-04-11 17:07
Yes, that's the expected behavior.
It makes this one work:

```elisp
(defhydra hydra-goto-line (global-map "M-g"
                           :pre (linum-mode 1)
                           :after-exit (linum-mode -1)
                           :exit t)
  ("g" goto-line "line")
  ("c" goto-char "char"))
```

If you don't want the code after each command, don't use `:after-exit`.

**Comment by jhonnyseven** [comment] 2015-04-11 17:38
I thought `:after-exit` was going to be something called after exit heads only not after every head. Something exactly like the old `:post`.

**Comment by abo-abo** [comment] 2015-04-11 17:46
The old `:post` is still available. `:after-exit` is useful for this one hydra that I mentioned.
If you find a use-case where `:post` or `:after-exit` isn't enough, just post it and I'll try to fit it in.
And please no abstract `test-a`/`test-b` stuff, the whole source of confusion is that I don't know what you actually want to do.

**Comment by jhonnyseven** [comment] 2015-04-11 18:02
This is pretty much as is from my hydras. When in `normal` hydra and region is not active I want `df` to kill the sexp forward and return back to `normal` hydra. When region is active `d` just kills the region. This used to work before the position of `:post` in relation to the head command changed.
```emacs-lisp
(defhydra select (:color teal)
  "select"
  ("f" (progn (set-mark (point)) (call-interactively 'forward-sexp))))

(defhydra normal (:color amaranth)
  "normal"
  ("d" (if (region-active-p)
	   (visit-hydra-call-and-return 'kill-region)
	 (visit-hydra-push
	  'select/body t
	  (lambda ()
	    (when (region-active-p)
	      (kill-region (region-beginning) (region-end)))
	    (normal/body))))
   :exit t))
```

**Comment by abo-abo** [comment] 2015-04-11 18:32
I think you should remove `select` and use this:

```elisp
(defhydra normal (:color amaranth)
  "normal"
  ("d" (if (region-active-p)
           (kill-region (region-beginning)
                        (region-end))
         (kill-sexp 1)))
  ("q" nil))
```

**Comment by jhonnyseven** [comment] 2015-04-11 18:51
Let's go a bit further. Without active region `re` deletes from point
to end of line and exits `normal` hydra. Without active region `de`
deletes from point to end of line.

```emacs-lisp
(defhydra select (:color teal)
  "select"
  ("f" (progn (set-mark (point)) (call-interactively 'forward-sexp)))
  ("e" (progn (set-mark (point)) (end-of-line))))

(defhydra normal (:color amaranth)
  "normal"
  ("d" (if (region-active-p)
	   (visit-hydra-call-and-return 'kill-region)
	 (visit-hydra-push
	  'select/body t
	  (lambda ()
	    (when (region-active-p)
	      (kill-region (region-beginning) (region-end)))
	    (normal/body))))
   :exit t)
  ("r" (if (region-active-p)
	   (delete-region-if-any)
	 (visit-hydra-push
	  'vi-select/body t
	  (lambda ()
	    (if (region-active-p)
		(kill-region (region-beginning) (region-end))
	      (vi-movement/body)))))
   :exit t))
```

**Comment by abo-abo** [comment] 2015-04-11 19:17
Still, it's not all code. Anyway, this can work:

```elisp
(defvar hydra-action nil)

(defhydra hydra-select (:color teal
                        :after-exit (funcall hydra-action))
  "select"
  ("f" (progn (set-mark (point)) (call-interactively 'forward-sexp)))
  ("e" (progn (set-mark (point)) (end-of-line))))


(defhydra hydra-normal (:color teal)
  "normal"
  ("d" (if (region-active-p)
           (kill-region (region-beginning)
                        (region-end))
         (setq hydra-action 'delete-active-region)
         (hydra-select/body)))
  ("r" (if (region-active-p)
           (delete-region
            (region-beginning)
            (region-end))
         (setq hydra-action (lambda ()))
         (hydra-select/body)))
  ("q" nil))
```

**Comment by jhonnyseven** [comment] 2015-04-11 19:45
Now `d` deletes and exits `normal` when it should just delete.

`hydra-normal` should be amaranth , add these two movement heads in there:
```
("h" backward-word)
  ("l" forward-word)
```

I can upload the whole thing if you think it's helpful. It's currently over 1000 lines.

**Comment by jhonnyseven** [comment] 2015-04-12 06:48
I patched hydra.el with a new `:after` thingy, so you don't have to spend more time with this. Thanks for the help though!

**Comment by abo-abo** [comment] 2015-04-12 10:59
> I patched hydra.el with a new :after thingy, so you don't have to spend more time with this. Thanks for the help though!

Alright, but I can patch it as well if you want. I don't really care
much about `:post` or `:before-exit` as long as the existing published
hydras that use them still work.  The current arrangement was just the
convenient thing to do after the last major rewrite.

**Comment by jhonnyseven** [comment] 2015-04-13 08:15
If I've understood corretly currently red and blue heads have this order for the hooks:
- `:pre`
- `:before-exit`/`:post`
- `command`
- `:after-exit`

What I added was for blue/teal heads only a new hook that comes after `:after-exit`.

What would be really nice is some hook that gets called after a command that exits the hydra (even if the head is red) and after any other way the hydra can be exited. For example it would get called after the exit caused by `switch-frame`.

**Comment by abo-abo** [comment] 2015-04-13 08:53
> What would be really nice is some hook that gets called after a
> command that exits the hydra (even if the head is red) and after any
> other way the hydra can be exited. For example it would get called
> after the exit caused by switch-frame.

Can't you just use `:after-exit` for that? It will always be called
after the command, whether it exited or not.  If you set
`:before-exit`, then `hydra-curr-on-exit` isn't nil. But it's set to
nil when a hydra exits. Then just check if `hydra-curr-on-exit` is nil
in `:after-exit`. The notation can be simplified later, once it works.

**Comment by jhonnyseven** [comment] 2015-04-13 09:28
I'll see what I'll do once the dust settles, so to speak :)
