### ISSUE TITLE
hydra hint not showing w/o explicit key binding?

### ISSUE THREAD

**Issue by seabadger** [abo-abo/hydra#282] opened 2018-02-02 19:08 UTC
Perhaps I'm misunderstanding something, but I thought that specifying an 'awesome-map' in the hydra specification would  set up the key binding AND allow the hint to be shown. 
However, that's not happening. 
If I run the following in a pristine emacs (emacs -Q) session:
```
(progn
  (add-to-list 'load-path "~/.dotfiles/emacs/elpa/hydra-20171120.1042/")
  (require 'hydra)

  (defhydra hydra-zoom (global-map "<f2>")
    "zoom"
    ("g" text-scale-increase "in")
    ("l" text-scale-decrease "out"))  
  )
```
and then press F2, I only see 'f2-' in the echo area, and no hint (the hydra functions fine if I know what to press).

If I explicitly set a key to invoke hydra-zoom/body, then the hint is shown.
Did I misunderstand the purpose of the awesome-map spec, or is this a bug?
Thanks...

**Comment by abo-abo** [comment] 2018-02-03 17:14
See this snippet from the README:

```elisp
(define-key global-map [f2 103]
  (function hydra-zoom/text-scale-increase))
(define-key global-map [f2 108]
  (function hydra-zoom/text-scale-decrease))
```

To put the above code into more familiar terms:

```elisp
(global-set-key (kbd "<f2> g") 'hydra-zoom/text-scale-increase)
(global-set-key (kbd "<f2> l") 'hydra-zoom/text-scale-decrease)
```

So you see, nothing is bound to `<f2>` directly, it's a prefix just like the built-in `C-x`.

PR welcome to clarify README if necessary.

**Comment by yuezhu** [comment] 2018-10-31 14:48
The keybinding for `hydra` needs to be separate in order to show the hint message when `<f2>` is pressed. For example, I configured `hydra` via [`use-package`](https://github.com/jwiegley/use-package) that should meets your requirement:
```
(use-package hydra
  :ensure t
  :bind (("C-c z" . hydra-zoom/body)
         ("C-c m". hydra-move/body))
  :config
  (defhydra hydra-zoom ()
    "zoom in/out font"
    ("=" text-scale-increase "zoom in")
    ("-" text-scale-decrease "zoom out"))

  (defhydra hydra-move ()
    "enlarge/shrink current window, or balance all windows"
    ("=" enlarge-window-horizontally "enlarge horizontally")
    ("-" shrink-window-horizontally "shrink horizontally")
    ("[" enlarge-window "enlarge vertically")
    ("]" shrink-window "shrink vertically")
    ("b" balance-windows "balance windows")))
```

**Comment by abo-abo** [comment] 2019-02-05 14:04
Closing as not a bug.

**Closed by abo-abo** 2019-02-05 14:04 UTC
