### ISSUE TITLE
A recent change breaks find-file-other-window, switch-to-buffer-other-window, etc.

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/hydra#124] opened 2015-04-28 05:37 UTC
I have this hydra (reduced from the actual one) which has been working as expected as of the MELPA version 20150423.653. It started behaving oddly after I upgraded to MELPA version 20150427.530:
```elisp
(bind-key "C-c t"
(defhydra foo (:exit nil)
  "
   foo
   .
"
  ("f" find-file)
  ("F" find-file-other-window)
  ("b" switch-to-buffer)
  ("B" switch-to-buffer-other-window)
  ("<escape>" nil)))
```
When this hydra is working, the "F" and "B" heads select or create the "other window" just as one would expect - when there is only one window, a new one is created by splitting, when there are two, the other is selected.

When it is not working, a new window is created even when there are two already. Sometimes the new window takes the place that was occupied by the LV window:

![screen shot 2015-04-27 at 9 55 59 pm](https://cloud.githubusercontent.com/assets/4935788/7363262/6f9ea40c-ed2c-11e4-8522-635ad3047506.png)

Sometimes it is created by splitting on the right of the LV window:

![screen shot 2015-04-27 at 10 03 04 pm](https://cloud.githubusercontent.com/assets/4935788/7363264/762b767e-ed2c-11e4-9721-6601b2e0d42c.png)

(Once the problem reproduced, I took screenshots after making the frame smaller to avoid large images. Please follow the solid box cursor to find the "new window" created.)

It feels that when it is not work, the LV window itself is included in consideration for choosing the "other window".

The problem seems to happen only when the current frame (I use only one Emacs frame almost all the time) is large enough - it reproduces reliably with full screen (by `toggle-frame-fullscreen`) or maximized (either by `toggle-frame-maximized` or dragged manually).

Reproduced with:
- http://emacsformacosx.com/: "GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org"
- https://github.com/railwaycat/homebrew-emacsmacport/releases/tag/emacs-24.5-mac-5.7

**Comment by zhaojiangbin** [comment] 2015-04-28 05:50
UPDATE: When the problem shows up as in the second screenshot, moving the cursor (or something else) to cause the window to repaint, the LV buffer content drawn on the left side disappears and is replaced with buffer content of the new window. In other words, it becomes as in the first screenshot.

**Comment by abo-abo** [comment] 2015-04-28 08:42
I can't reproduce on GNU/Linux Emacs 24.5.  The change that brought it is probably [this one](https://github.com/abo-abo/hydra/commit/00d2c0c6f97fe2910849cdc4cddb77d24bc73e51#diff-53aefabd162656ccc9c5170ecaf5429dL390).  But since I also have this code:

    (set-window-dedicated-p lv-wnd t)

`display-buffer` (used by `find-file-other-window` etc.) should avoid using `lv-wnd`.  So it's probable that you've found an Emacs bug.  You can try to reproduce it better with just:

    (lv-message "foo")

and then calling `switch-to-buffer-other-window` interactively until the error occurs.

**Comment by zhaojiangbin** [comment] 2015-04-28 15:42
Yeah, given how it is related with the frame size, I am, too, suspecting that this is an Emacs bug.

With `(lv-message "foo")` followed by `M-x switch-to-buffer-other-window`, it reproduces and looks similar to the second screenshot, except that the new window is a real one. Tested with MELPA version 20150428.50 which has `lv-force-update` set to nil by default.

I understand that if you cannot reproduce it yourself, you will have difficulty fixing it. Is it possible to resurrect the old behavior as an option? I wish my lisp skill could be of more help.

**Comment by kaushalmodi** [comment] 2015-04-28 15:43
+1

I came here to open a similar bug report and found this already posted.

When I try to call `diff-hl-revert-hunk` or a similar command from the `diff-hl` package, the new window spits up the lv window instead of the window from which I executed this command.

In essence, the lv window is treated like a normal window by emacs; it should be treated like a minibuffer window instead.

This happens **only if I call a command requiring window splitting if the frame already has 2+ windows**. If the frame has just 1 window and if I call the same hydra head, the issue does not repeat.

Here is my hydra for diff-hl: https://github.com/kaushalmodi/.emacs.d/tree/01eda4d12b94664004a7a54cdce4115ecd1cb709/setup-files/setup-diff-hl.el#L21

Here is what the problem looks like:
![clipboard01](https://cloud.githubusercontent.com/assets/3578197/7373597/78730446-ed9b-11e4-86fa-d49aa6ee6537.png)

Note that the lv window is split and it tries to show the diff on the right hand side in that 1 line tall window.

**Comment by kaushalmodi** [comment] 2015-04-28 15:52
The issue is analogous to this behavior:

1. `M-: (lv-message "foo")`
2. Select that lv window using mouse
3. `C-x 3` -> lv window will be split

Can you put in a fail safe so that the lv window can never be selected (using mouse or any other means, just as it cannot be selected using `C-x o`)?

If the lv window can never be selected by any means, then it can also be not split by any command.

My assumption is that when I call that hydra head, it somehow selects the lv window and splits that instead of selecting a non-lv window for splitting.

**Comment by abo-abo** [comment] 2015-04-28 16:27
> Can you put in a fail safe so that the lv window can never be selected (using mouse or any other means, just as it cannot be selected using C-x o)?

I've already marked it as a dedicated window. So, strictly speaking, this whole thing is an Emacs bug.
From here:

- I can either put some code into Hydra to work-around the said bug, like I did before.
- Or I can try to fix it in the core.

I'd rather not go with the first option, because it will result in a (small) problem of the docstring flickering when you hold a red head key: after every key-down event, the window will have to be deleted and re-created.  With the current code, if the docstring hasn't changed, LV-window will simply be left the same.  With the old code, before this bug, the window was deleted and re-created each time.

**Comment by kaushalmodi** [comment] 2015-04-28 16:34
If you can recreate this issue, can you please fix it in the core and for the time being provide a switch (defvar) to revert to the old method? 

Once the bug is fixed in emacs, you can remove that var and the change should be transparent to the users.

**Closed** 2015-04-28 16:46 UTC

**Comment by zhaojiangbin** [comment] 2015-04-28 16:49
By the way, I noticed that when this issue is happening, the `*LV*` buffer is included in the buffer list by `switch-to-buffer`, while in an older version of hydra that does not have this issue the `*LV*` buffer is not in the buffer list. Hope this helps.

**Comment by abo-abo** [comment] 2015-04-28 17:00
> By the way, I noticed that when this issue is happening, the *LV* buffer is included in the buffer list by switch-to-buffer, while in an older version of hydra that does not have this issue the *LV* buffer is not in the buffer list. Hope this helps.

Yes, I'm aware of this. In the change that I made, I chose not to delete `*LV*` each time before calling a head, only to re-create it afterwards, but instead to keep it.  I thought that marking `*LV*` as a dedicated window would prevent Emacs from touching it. Apparently, this assumption currently doesn't hold. So I've reverted the change temporarily, with an option to turn it back on via a variable.

**Comment by kaushalmodi** [comment] 2015-04-28 17:59
@abo-abo Thanks. This issue is now fixed for me.

**Comment by zhaojiangbin** [comment] 2015-04-29 16:34
Thanks for the fix.

But the docstring for the variable `hydra--work-around-dedicated` seems to be wrong. It says ```When non-nil, assume there's no bug in `pop-to-buffer' selecting a dedicated window.```

In my tests, it is the opposite - When the variable has t (which is the default), the problem disappears. When I set it to nil, it came back.

I am assuming that this variable is to work around a bug in `pop-to-buffer`. Am I understand it correctly?

**Comment by abo-abo** [comment] 2015-04-29 16:47
> But the docstring for the variable hydra--work-around-dedicated seems to be wrong. It says When non-nil, assume there's no bug in `pop-to-buffer' selecting a dedicated window.

This is correct. Currently there *is* a bug in `pop-to-buffer`, it hasn't been fixed yet.  So if you set `hydra--work-around-dedicated` to `nil` you'll encounter the bug.  You may still choose to do it, if you don't care about that particular bug.
