### ISSUE TITLE
Taller header-line :line-width value causes cut off bottom in hydra

### ISSUE THREAD

**Issue by asimpson** [abo-abo/hydra#266] opened 2017-10-24 15:15 UTC
![napkin 10-24-17 11 12 07 am](https://user-images.githubusercontent.com/1048831/31951456-2d02ef2e-b8ac-11e7-9dbb-945077790794.png)

My header line is set to this:
``` elisp
(set-face-attribute 'header-line nil
    :box `(:line-width 3 :color ,(plist-get base16-ocean-colors :base02) :style nil))
```

and the demo hydra in the screenshot is:
```elisp
(use-package hydra
  :defer 1
  :config (progn
    (global-set-key (kbd "C-c a") 'hydra-text/body)
  )
)

(defhydra hydra-text ()
  "
    zoom
    ----
    Here are the options:
    ---
    _g_ zoom
    _l_ back
  "
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))
```

Changing the `:line-width` value from 3 to 1 fixes the issue. Is this an issue hydra can address? Or do I have to pick between hydra versus a bit fatter header line?

**Comment by abo-abo** [comment] 2017-10-24 16:49
I can't reproduce with:

    (set-face-attribute 'header-line nil :box `(:line-width 3 :color "blue" :style nil))

Can you reproduce with `emacs -Q`?

**Comment by asimpson** [comment] 2017-10-24 17:20
@abo-abo ah I left out an important part of my config 🤦‍♂️ 

```elisp
(defun simpson-header()
    (setq header-line-format "foo"))

(simpson-header)

(add-hook 'buffer-list-update-hook 'simpson-header)

(set-face-attribute 'header-line nil
    :box `(:line-width 3 :color "blue" :style nil))

(add-to-list 'load-path "~/.emacs.d/elpa/hydra-20170924.2259/")
(load "hydra")

(defhydra hydra-text ()
  "
    zoom
    ----
    Here are the options:
    ---
    _g_ zoom
    _l_ back
  "
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))

(global-set-key (kbd "C-c a") 'hydra-text/body)
```

Drop this in scratch in an `emacs -Q` and then `eval-buffer`.

**Comment by asimpson** [comment] 2017-10-27 17:38
@abo-abo after thinking about this more, is there a way to determine if I'm in a hydra to set the hydra buffer `header-line-format` to nil?

**Comment by WJCFerguson** [comment] 2018-05-14 15:55
I'm also interested in this - if we have `header-line-format` set for most buffers, what's the easiest way to have it nil for hydra buffers?  As it is, having it set causes us to lose the bottom line of the hydra.

**Comment by abo-abo** [comment] 2018-05-14 17:52
@asimpson Sorry for the slow response. The fix is quite simple, the buffer name that hydra uses is always `" *LV*"`.
I verified that this change works:

```elisp
(defun simpson-header()
  (unless (equal (buffer-name) " *LV*")
    (setq header-line-format "foo")))
```

@WJCFerguson Will this fix your issue as well?

**Comment by WJCFerguson** [comment] 2018-05-14 18:26
Hmmm, I suppose I could just follow the orig example here and set header-line-format from `buffer-list-update-hook.

**Comment by WJCFerguson** [comment] 2018-05-14 18:29
and that does indeed work fine, rather than the setq-default method.   Thanks.

**Comment by abo-abo** [comment] 2018-05-14 18:58
OK, closing this issue as fixed. Thanks for verifying.

**Closed by abo-abo** 2018-05-14 18:58 UTC
