### ISSUE TITLE
Unbind key-chord when hydra is active

### ISSUE THREAD

**Issue by jagrg** [abo-abo/hydra#97] opened 2015-03-27 12:45 UTC
Consider the following example.

```
(defhydra hydra-zoom (global-map "<f2>")
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))

(key-chord-define-global "gg" (lambda() (interactive)(find-file "~/.emacs.d/notes.org")))
```

I would like to be able to press `g` consecutively when hydra is active without running key-chord. Any idea?

**Comment by abo-abo** [comment] 2015-03-27 13:05
Here's the way to do it with the current Hydra code:

```cl
(defvar hydra-zoom-imf nil)
(defhydra hydra-zoom (global-map "<f2>"
                      :pre (unless hydra-zoom-imf
                             (setq hydra-zoom-imf input-method-function)
                             (setq input-method-function nil))
                      :post (progn
                              (setq input-method-function hydra-zoom-imf)
                              (setq hydra-zoom-imf nil)))
  "zoom"
  ("g" text-scale-increase "in")
  ("l" text-scale-decrease "out"))
```

I don't know if Hydra should store/restore `input-method-function` by default, some users may be actually using it.

But `key-chord-mode` is rather cavalier with it, so I can assume that if a user has `input-method-function` set to `key-chord-input-method` it's OK to unset it temporarily.

I'll make the change to Hydra at some point today. In the meantime, check if the code above works.

**Comment by jhonnyseven** [comment] 2015-03-27 13:23
I tried [this](https://github.com/search?utf8=%E2%9C%93&q=vi-nav%2Frestore-key-chord-mode&type=Code&ref=searchresults) but switched to just disabling on `:body-pre` and anabling on `:post` because jumping between hydras often let the key-chord mode disabled.

**Comment by jagrg** [comment] 2015-03-27 13:46
The code above does work, thanks!

**Comment by abo-abo** [comment] 2015-03-27 15:29
@jagrg, you can use your initial code now; it should work.

**Comment by jagrg** [comment] 2015-04-15 17:49
It stopped working. Have you changed anything?

**Comment by abo-abo** [comment] 2015-04-15 17:57
Yeah, fixing a different bug has caused this regression. Should be fixed now, thanks for noticing.

**Comment by cute-jumper** [comment] 2015-09-14 19:59
Not working again. It seems that reverting the changes introduced in https://github.com/abo-abo/hydra/issues/163 solves the problem.

**Comment by abo-abo** [comment] 2015-09-15 07:04
OK, I'll look at it again. Maybe there's a way to make both things work.

**Comment by abo-abo** [comment] 2015-12-14 12:20
Thanks, sorry for the delay.

Please test this one, and additionally other places with key-chord interaction.

**Closed** 2015-12-14 12:19 UTC

**Comment by cute-jumper** [comment] 2015-12-16 03:23
Thanks! I can confirm it works.
